services:
  - type: web
    name: link-preview-api
    env: node
    plan: free
    buildCommand: |
      npm install
      npx playwright install --with-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
